services:
  accounts:
    image: "mjawaad/accounts:s4"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mjawaad
  loans:
    image: "mjawaad/loans:s4"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mjawaad
  cards:
    image: "mjawaad/cards:s4"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mjawaad
networks:
  mjawaad:
    driver: "bridge"
