server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"
    
build:
  version: "1.0"
     
loans:
  message: "Welcome to icici bank micro services"
  contactDetails:
    name: "Mohammed Jawaad"
    email: "mj@gmail.com"
  onCallSupport:
    - 9916403863
    - 8660028318
