services:
  accountsdb:
    container_name: accountsdb
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice_db_config   

  loansdb:
    container_name: loansdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice_db_config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice_db_config      

  configserver:
    image: "mjawaad/configserver:s7"
    container_name: configserver_ms
    ports:
      - "8071:8071"
    healthcheck:
     test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
     interval: 10s
     timeout: 5s
     retries: 10
     start_period: 10s 
    extends:
      file: common-config.yml
      service: microservice_base_config

  accounts:
    image: "mjawaad/accounts:s7"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    depends_on:
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice_configserver_config

  loans:
    image: "mjawaad/loans:s7"
    container_name: loans_ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice_configserver_config

  cards:
    image: "mjawaad/cards:s7"
    container_name: cards_ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice_configserver_config

            
networks:
  mjawaad:
    driver: "bridge"
